### ISSUE TITLE
Peak-driver-linux module not built

### ISSUE THREAD

**Issue by VincentDaanen** [Pelagicore/meta-bistro#161] opened 2018-04-11 18:44 UTC
Hi,

I try to build the peak-linux-driver. 
When I call bitbake core-image-rt, I can see that the tasks of the recipe peak-linux-driver are executed but pcan.ko is not added to the rootfs and I cannot find any file pcan.ko in the tmp directory (and subdirectories).
Did someone experience the same issue?
Vincent

**Comment by tobsan** [comment] 2018-04-12 06:12
Hi @VincentDaanen.

I believe the issue is that ``core-image-rt`` does not ``IMAGE_INSTALL`` the ``peak-linux-driver``. But on the other hand, then it shouldn't build it either.

Did you find a ``peak-linux-driver.rpm`` in ``tmp/deploy/<arch>/rpm`` (assuming you use rpm output)? If you have the rpm, you can list the files in it by issuing ``rpm -qlp <file>``. It could be that the rpm also gets a ``kernel-module`` prefix.

If you don't have the RPM, or anyway if it's not included on your image, you should create a new image that reuses `core-image-rt` and adds `peak-linux-driver`. I haven't tried the below so the path might be slightly off.

```
require meta/recipes-rt/images/core-image-rt.bb

IMAGE_INSTALL += peak-linux-driver
```

**Comment by tobsan** [comment] 2018-04-12 11:41
I just made a test-build myself and there seems to be some issue with the recipe. Yocto believes the build succeeds, but the log says otherwise:

```
DEBUG: Executing shell function do_compile
NOTE: make -j 12 NET=NETDEV_SUPPORT KERNEL_LOCATION=/home/pelux/pelux-master/build/tmp/work-shared/intel-corei7-64/kernel-source KERNEL_PATH=/home/pelux/pelux-master/build/tmp/work-shared/intel-corei7-64/kernel-source KERNEL_VERSION=4.9.81-intel-pk-standard CC=x86_64-pelux-linux-gcc  -fuse-ld=bfd LD=x86_64-pelux-linux-ld.bfd  AR=x86_64-pelux-linux-ar  O=/home/pelux/pelux-master/build/tmp/work-shared/intel-corei7-64/kernel-build-artifacts KBUILD_EXTRA_SYMBOLS=
make[1]: Entering directory `/home/pelux/pelux-master/build/tmp/work/intel_corei7_64-pelux-linux/peak-linux-driver/7.9-r0/peak-linux-driver-7.9/driver'
Makefile:102: *** "Can't find /home/pelux/pelux-master/build/tmp/work-shared/intel-corei7-64/kernel-source/include/linux/version.h".  Stop.
make[1]: Leaving directory `/home/pelux/pelux-master/build/tmp/work/intel_corei7_64-pelux-linux/peak-linux-driver/7.9-r0/peak-linux-driver-7.9/driver'
make[1]: Entering directory `/home/pelux/pelux-master/build/tmp/work/intel_corei7_64-pelux-linux/peak-linux-driver/7.9-r0/peak-linux-driver-7.9/driver'
Makefile:102: *** "Can't find /home/pelux/pelux-master/build/tmp/work-shared/intel-corei7-64/kernel-source/include/linux/version.h".  Stop.
make[1]: Leaving directory `/home/pelux/pelux-master/build/tmp/work/intel_corei7_64-pelux-linux/peak-linux-driver/7.9-r0/peak-linux-driver-7.9/driver'
make[1]: Entering directory `/home/pelux/pelux-master/build/tmp/work/intel_corei7_64-pelux-linux/peak-linux-driver/7.9-r0/peak-linux-driver-7.9/lib'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
# ln -sf ../driver/pcan.h pcan.h
x86_64-pelux-linux-gcc  -fuse-ld=bfd src/libpcan.c -fPIC -shared -O2 -Wall -Wl,-soname,libpcan.so.0 -lc -I. -I../driver -DNO_RT -o libpcan.so.0.6
src/libpcan.c:38:10: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
          ^~~~~~~~~~
compilation terminated.
make[1]: *** [libpcan.so.0.6] Error 1
make[1]: Leaving directory `/home/pelux/pelux-master/build/tmp/work/intel_corei7_64-pelux-linux/peak-linux-driver/7.9-r0/peak-linux-driver-7.9/lib'
make[1]: Entering directory `/home/pelux/pelux-master/build/tmp/work/intel_corei7_64-pelux-linux/peak-linux-driver/7.9-r0/peak-linux-driver-7.9/test'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
x86_64-pelux-linux-gcc  -fuse-ld=bfd src/receivetest.c src/common.c -I. -I../lib -I../driver -L../lib -o receivetest   -lpcan -DNO_RT
src/receivetest.c:40:10: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
          ^~~~~~~~~
compilation terminated.
src/common.c:34:10: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
          ^~~~~~~~~
compilation terminated.
make[1]: *** [receivetest] Error 1
make[1]: Leaving directory `/home/pelux/pelux-master/build/tmp/work/intel_corei7_64-pelux-linux/peak-linux-driver/7.9-r0/peak-linux-driver-7.9/test'
DEBUG: Shell function do_compile finished
```

I'll look into it more!

**Comment by tobsan** [comment] 2018-04-20 08:30
Assigning this to @GordanM temporarily, since I won't be able to work on this issue anymore.

**Comment by GordanM** [comment] 2018-04-20 09:25
Alright @tobsan , thanks!

**Closed** 2018-08-14 14:02 UTC
